# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65cbd3beafaf763bd59610c783f6676154a54715c7ea5da8124fe99e250f1a8a7c75f4d11c5cdc732d9b4ea317e9e2b8eb4c40f13eeaff71ba79480a8d20aeaa

test:
  secret_key_base: 12d43d87dccc5e57ca095f9ab04b47809c44a646155552d90c13da8f6c23d5bd312488343cfff3a1f1480d766109a0cc72428eefe4836cd7ce5d4a1ec70bd166

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
